In [1]:
!pip install numpy

In [2]:
import numpy as np
arr=np.array([1,2,3])
print("list to array : ",arr)
print(arr[2])

list to array :  [1 2 3]
3


In [3]:
import numpy as np
arr1=np.array([[1,2,3],[3,6,9]])
print("array is : \n",arr1)

array is : 
 [[1 2 3]
 [3 6 9]]


In [4]:
arr=np.array((1,2,3))
print("tuple to array : ",arr)

tuple to array :  [1 2 3]


In [5]:
arr1=np.array([[1,2,3],[3,6,9]])
print("array accessing : ",arr1[0][1])
print(arr1[0][0])
print(arr1[1][1])

array accessing :  2
1
6


In [6]:
arr=np.array((1,2,3))
print("tuple to array : ",arr)

tuple to array :  [1 2 3]


In [7]:
arr1=np.array([[1,2,3],[3,6,9]])
print("array accessing : ",arr1[0][1])
print(arr1[0][0])
print(arr1[1][1])

array accessing :  2
1
6


In [8]:
arr=np.array([[[1,2,3],[3,6,9]],[[2,4,6],[8,10,12]]])
print("3D mtrx : \n",arr)
print(arr[0,1,2]) #0 implies the frst 2d mtrx and the others -> index
print(arr[1,1,2])

3D mtrx : 
 [[[ 1  2  3]
  [ 3  6  9]]

 [[ 2  4  6]
  [ 8 10 12]]]
9
12


In [9]:
arr=np.array([[1,2,3],[3,6,9],[2,4,6],[8,10,12]])
print("2D mtrx : \n",arr)

2D mtrx : 
 [[ 1  2  3]
 [ 3  6  9]
 [ 2  4  6]
 [ 8 10 12]]


In [10]:
#SLICING OF ARRAY

arr=np.array([0,1,2,3,4,5,6,7,8,9,10])
print(arr[1:5])
print(arr[0:8])
print(arr[::2])
print(arr[1::2])  # [strt:end:step]

[1 2 3 4]
[0 1 2 3 4 5 6 7]
[ 0  2  4  6  8 10]
[1 3 5 7 9]


In [11]:
arr=np.array([[1,2,3,4,5],[10,20,30,40,50]])
print("2D array is\n",arr,"\n")
print("\n",arr[1,1:4])
print("\n",arr[1,1:4:2])

print("\n",arr[0,1:3])
print("\n",arr[0,1:4:2])

print("\n",arr[0:2,2])    # datas of 2 column
print("\n",arr[0:2,0:3])  # here 0:2 implies 0,1 rows
print("\n",arr[0:1,0:3])  # here 0:1 implies 0th rows

print("\n",arr[0:2,0:5:2])
print("\n",arr[:,::2])   

2D array is
 [[ 1  2  3  4  5]
 [10 20 30 40 50]] 


 [20 30 40]

 [20 40]

 [2 3]

 [2 4]

 [ 3 30]

 [[ 1  2  3]
 [10 20 30]]

 [[1 2 3]]

 [[ 1  3  5]
 [10 30 50]]

 [[ 1  3  5]
 [10 30 50]]


In [12]:
arr=np.array([[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]])
print("\n",arr,"\n")
print("Here step size is 1\n",arr[0:3,0:5:3])
print("\nHere step size is 2\n",arr[0:3:2,0:5:3])
print("\nHere step size is 3\n",arr[0:3:3,0:5:3])
print("\n",arr[::,::2]) 
print("\n",arr[::2,::2])


 [[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [100 200 300 400 500]] 

Here step size is 1
 [[  1   4]
 [ 10  40]
 [100 400]]

Here step size is 2
 [[  1   4]
 [100 400]]

Here step size is 3
 [[1 4]]

 [[  1   3   5]
 [ 10  30  50]
 [100 300 500]]

 [[  1   3   5]
 [100 300 500]]


In [13]:
print((type(arr)))
print(arr.dtype)
print(arr.shape)

arr1=np.array([[[1,2,3],[3,6,9]],[[2,4,6],[8,10,12]]])
print(arr1.shape)

<class 'numpy.ndarray'>
int32
(3, 5)
(2, 2, 3)


In [14]:
#MATRIX ADDITION

a1=np.array([[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]])
a2=np.array([[1,3,5,7,9],[11,22,33,44,55],[66,77,88,99,111]])
print(a1,"\n")
print(a2,"\n")
sum=a1+a2
print("Addition of 2 matrx : \n",sum)

[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [100 200 300 400 500]] 

[[  1   3   5   7   9]
 [ 11  22  33  44  55]
 [ 66  77  88  99 111]] 

Addition of 2 matrx : 
 [[  2   5   8  11  14]
 [ 21  42  63  84 105]
 [166 277 388 499 611]]


In [15]:
#MATRIX MULTIPLICATION

a1=np.array([[1,2,3],[10,20,30],[100,200,300]])
a2=np.array([[1,3,5],[11,22,33],[66,77,88]])
print(a1,"\n")
print(a2,"\n")
print("Matrix multiplication : \n\n",np.dot(a1,a2))

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] 

[[ 1  3  5]
 [11 22 33]
 [66 77 88]] 

Matrix multiplication : 

 [[  221   278   335]
 [ 2210  2780  3350]
 [22100 27800 33500]]


In [16]:
a1=np.array([[1,2,3],[10,20,30],[100,200,300]])
a2=np.array([[1,3,5],[11,22,33],[66,77,88]])

print(a1@a2)
print(a1*a2)

[[  221   278   335]
 [ 2210  2780  3350]
 [22100 27800 33500]]
[[    1     6    15]
 [  110   440   990]
 [ 6600 15400 26400]]


In [17]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[::-1])   #REVERSE
arr.resize(5,2)
print(arr)


[10  9  8  7  6  5  4  3  2  1]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [18]:
arr=np.arange(5)
a=np.arange(12,38)
arr1=np.arange(15)
print(arr)
print(a)
print(arr1)

[0 1 2 3 4]
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [20]:
n=np.random.random([3,3])
print(n)

[[0.90860178 0.49572812 0.72685298]
 [0.22316541 0.66251838 0.74370574]
 [0.17994592 0.07072612 0.44994061]]


In [21]:
z=np.array([[1+0.j,2+5.j]])
print(z)
print(z.real)
print(z.imag)

[[1.+0.j 2.+5.j]]
[[1. 2.]]
[[0. 5.]]


In [22]:
z=np.array([[1,2],[3,4]],dtype=complex)
print(z)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [24]:
q=np.ones((5,5))
print(q)

w=np.zeros((5,5))
print(w)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
print("1 on the border and 0 inside the array : \n")
q[1:4,1:4]=0   #q[1:-1,1:-1]=0 
print(q)

1 on the border and 0 inside the array : 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
z=np.ones((8,8))
z[0::2,0::2]=0
z[1::2,1::2]=0
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [27]:
z=np.zeros((8,8))
z[0::2,0::2]=1
z[1::2,1::2]=1
print(z)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
