# VECTORIZATION

In [1]:
import time
time.ctime()

'Mon Jan 31 16:52:28 2022'

In [2]:
import time
import numpy as np
size=20

# LIST

list=range(size)
start_list=time.time()

sum=0
for i in list:
    sum=sum+i
print("Sum : ",sum)
print("Time taken",time.time()-start_list)



arr=np.arange(size)
start_array=time.time()
sum=np.sum(arr)

print("Sum : ",sum)
print("Time taken",time.time()-start_list)

Sum :  190
Time taken 0.0007495880126953125
Sum :  190
Time taken 0.0017502307891845703


In [3]:
#TRANSPOSE

arr=np.array([[1,2,3],[10,20,30],[100,200,300]])
print("Array is \n",arr)
a=np.transpose(arr)
print("Transpose of the array is \n",a)

Array is 
 [[  1   2   3]
 [ 10  20  30]
 [100 200 300]]
Transpose of the array is 
 [[  1  10 100]
 [  2  20 200]
 [  3  30 300]]


In [4]:
import numpy as np
from numpy import linalg
arr=np.array([[8,3],[2,6]])
print("Determinant : \n",np.linalg.det(arr))
print("Inverse : \n",np.linalg.inv(arr))

Determinant : 
 41.999999999999986
Inverse : 
 [[ 0.14285714 -0.07142857]
 [-0.04761905  0.19047619]]


In [7]:
import numpy as np
a=np.array([[2,2,1],[1,3,1],[1,2,2]])
print("a =\n ",a)
w,v=np.linalg.eig(a)
print("Eigen Values : ",w)
print("Eigen vectors :\n\n ",v)

a =
  [[2 2 1]
 [1 3 1]
 [1 2 2]]
Eigen Values :  [5. 1. 1.]
Eigen vectors :

  [[ 0.57735027  0.16903085 -0.79970556]
 [ 0.57735027 -0.50709255  0.53555105]
 [ 0.57735027  0.84515425 -0.27139654]]
